pipeline {
    environment {
        APP_NAME = 'REPLACE_ME_APP_NAME'
	    DOCKER_REPO = 'REPLACE_ME_IMAGE_REPO'
    }
    agent any
    stages {
        stage("CI Config Analysis") {
            steps {
                script {
                    ciConfigAnalysis
                }
            }
        }
	    stage('Build & Push Image') {
            agent {
                docker {
                    image 'xcomponent/mono-node-git:1.4.0'
                    args '-u root -v $HOME/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker'
                }
            }
            steps {
                sh 'yarn install'
		        sh 'yarn build'
                sh 'docker build -t $DOCKER_REPO$APP_NAME:$IMAGE_TAG .'
		        sh 'docker push $DOCKER_REPO$APP_NAME:$IMAGE_TAG'
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'helm lint charts/$APP_NAME'
                    sh 'helm upgrade --kube-context $USE_K8S_CONTEXT --debug --install --set-string $SET_STRING $APP_NAME charts/$APP_NAME'
                    k8sHealthCheck $APP_NAME $K8S_NAMESPACE $K8S_HEALTH_CHECK_WAIT_TIME_Seconds $USE_K8S_CONTEXT
                }
            }
        }
    }
}