pipeline {
    environment {
        APP_NAME = 'REPLACE_ME_APP_NAME'
	DOCKER_REPO='REPLACE_ME_IMAGE_REPO'
    }
    agent any
    stages {
        stage("Check Env") {
            steps {
		script {
                    global.checkEnv()
                }
	    }
        }
	stage("Gen Image Tag") {
            steps {
                script {
                    global.genImageTag()
                }
            }
        }
	stage('Build & Push Image') {
            agent {
                docker {
                    image 'xcomponent/mono-node-git:1.4.0'
                    args '-u root -v $HOME/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker'
                }
            }
            steps {
                sh 'yarn install'
		sh 'yarn build'
                sh 'docker build -t $DOCKER_REPO$APP_NAME:$IMAGE_TAG .'
		sh 'docker push $DOCKER_REPO$APP_NAME:$IMAGE_TAG'
            }
        }
        stage('Deploy') {
            steps {
	        sh 'helm lint charts/$APP_NAME'
                sh 'helm upgrade --debug --install --set-string image.tag=$IMAGE_TAG,image.repository=$DOCKER_REPO,image.name=$APP_NAME $APP_NAME charts/$APP_NAME'
            }
        }
    }
}