pipeline {
    environment {
        APP_NAME = 'REPLACE_ME_APP_NAME'
	    DOCKER_REPO = 'REPLACE_ME_IMAGE_REPO'
    }
    agent any
    stages {
        stage("CI Config Analysis") {
            steps {
		        script {
                    ciConfigAnalysis()
                }
	        }
        }
	    stage('Test') {
            agent {
                docker {
                    image 'repository.xiaobao100.com/docker/library/dotnet-sonar-cn:4.6.2'
                }
            }
            steps{
              withSonarQubeEnv('sonarqube') {
                  sh "rm -rf .sonarqube"
                  sh "dotnet /sonar-scanner/SonarScanner.MSBuild.dll begin /k:$APP_NAME /d:sonar.cs.opencover.reportsPaths='**/coverage.opencover.xml'"
                  sh "dotnet build -c Release"
                  sh "rm -drf testResults"
                  sh (returnStatus: true, script: "find **/* -name \'*.csproj\' -print0 | xargs -L1 -0 -P 8 dotnet test --no-build -c Release --logger trx --results-directory testResults /p:CollectCoverage=true /p:CoverletOutputFormat=opencover")
                    step([$class: 'XUnitPublisher', testTimeMargin: '3000', thresholdMode: 1, thresholds: [[$class: 'FailedThreshold', unstableThreshold: '0']
                            , [$class: 'SkippedThreshold']], tools: [[$class: 'MSTestJunitHudsonTestType', deleteOutputFiles: true, failIfNotNew: false
                            , pattern: 'testResults/**/*.trx', skipNoTestFiles: true, stopProcessingIfError: true]]])
                  sh "dotnet /sonar-scanner/SonarScanner.MSBuild.dll end"
                }
            }
        }
        stage("Quality Gate") {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('Build & Push Image') {
            steps {
                sh "docker build -t $DOCKER_REPO$APP_NAME:$IMAGE_TAG ."
		        sh "docker push $DOCKER_REPO$APP_NAME:$IMAGE_TAG"
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh "helm lint charts/$APP_NAME"
                    sh "helm upgrade --kube-context $USE_K8S_CONTEXT --debug --install --namespace $K8S_NAMESPACE --set-string $SET_STRING $APP_NAME charts/$APP_NAME"
                    k8sHealthCheck("$APP_NAME", "$K8S_NAMESPACE", "$K8S_HEALTH_CHECK_WAIT_TIME_SECONDS", "$USE_K8S_CONTEXT")
                }
            }
        }
    }
}